### ISSUE TITLE
scope of the project?

### ISSUE THREAD

**Issue by danybeam** [mart1nro/joycontrol#2]
What is the intended scope for this project?
do you need (or even want) help?

I made my own fork for personal use but I figured I could PR evey now and then any changes I've made (i.e. I cleaned a little bit the structure of the project and made a small template for new scripts)

are you interested in that?
Obviously I can't help all the time because life 🤷‍♂ but I would gladly dip my toes in it 😄

**Comment by mart1nro** [comment]
It's mostly a fun side project. I'm thinking of two use cases:

Being able replay controls and automate repetitive tasks in some games. This is limited since delays are not consistent over the bluetooth connection. Though it still works, if timing doesn't matter too much.
Parsing the vibration reports should help with synchronization, so this is a feature I want to implement next.

Another use case could be using different controllers and relaying the commands over bluetooth or build your own controller with a Pi.

Currently I'm a bit stuck on the pairing. At some point input reports pile up, which causes the Switch not to get the replies in time and sends requests again. This makes the pairing inconsistent and sometimes it takes really long. After pairing is finished it works fine again. Gonna make an issue with more info on that once I have time.

I'm currently on vacation, so I won't do much for the next one and a half week or so.

If you have something to contribute and or have other interesting use cases I'd gladly appreciate any help.
