### ISSUE TITLE
Bluetooth class isn't changed properly

### ISSUE THREAD

**Issue by JuanPotato** [mart1nro/joycontrol#20]
At first joycontrol wouldnt work on my laptop (running an xps 13 9370) so I tried to figure out what was wrong. My phone showed a "pro controller" but with a laptop icon so I checked the class with hciconfig and it was set to `0x0c010c` for Laptop. I changed it to `0x002508` for Gamepad, ran joycontrol, but joycontrol seemed to revert it back to Laptop. I ran joycontrol and changed the class while it was running which worked. The switch connected and I was able to send inputs.

**Comment by mart1nro** [comment]
Interesting... It seems like the device class is reset when registering the SDP record. The Switch still connects fine for me though.

I created a pull request, where I set the device class after registering the SDP record. Please check if that works for you.

**Comment by JuanPotato** [comment]
I don't think this is needed since it was working in the end after enabling pairing

**Comment by Ruoruo-0v0** [comment]
@JuanPotato Sorry I think I might have a similar problem:

sudo python3 ./run_controller_cli.py PRO_CONTROLLER
[13:29:29] joycontrol.device set_name::69 INFO - setting device name to Pro Controller...
[13:29:29] joycontrol.device set_class::61 INFO - setting device class to 0x002508...
[13:29:29] joycontrol.utils run_system_command::75 DEBUG - ['hciconfig hci0 class 0x002508' exited with 0]
[13:29:29] joycontrol.server create_hid_server::84 INFO - Advertising the Bluetooth SDP record...
[13:29:29] joycontrol.server create_hid_server::94 INFO - Waiting for Switch to connect... Please open the "Change Grip/Order" menu.

Is this due to the same issue? How do I change the bluetooth class while it was running? Thanks!

**Comment by MasonLaney** [comment]
@Ruoruo-0v0 I had the same issue and think I just got it working. I used `sudo hciconfig hciX class 0x002508` and then ran joycontrol and it worked. Running joycontrol reset it though so I had to run the command first each time I wanted to start joycontrol.

**Comment by JaredEzz** [comment]
Changing the default class to 0x002508 in /etc/bluetooth/main.conf seems to be necessary to connect after the 12.0.0 update

**Comment by l0nkDev** [comment]
> Changing the default class to 0x002508 in /etc/bluetooth/main.conf seems to be necessary to connect after the 12.0.0 update

How do you do that exactly

**Comment by nfp0** [comment]
I'm also affected by this problem where joycontrol does not seem to set the `0x002508` class value correctly.

**Comment by nfp0** [comment]
@l0nkDev I think it's the Class setting in that file.
